#!/usr/bin/env python3
"""Generate include/tsumego_data.h from a tsumego collection.

The input is the collection ZIP (or an unpacked directory of .sgf files)
produced by the `tsumego-pdf` tool in https://github.com/filip131311/Tsumego
from Cho Chikun's "Encyclopedia of Life and Death - Elementary":

    cd Tsumego/tsumego-pdf
    cargo run --release --bin tsumego-pdf -- books/cho-1-elementary.pdf -o cho.zip
    ../../argentstars/tools/gen_tsumego.py cho.zip

Each problem is a single-root SGF with AB[]/AW[] setup stones in the top-left
corner. The header stores, per entry, the book's problem number and the
stones packed one byte each ((row << 4) | col), in a fixed pseudo-random
order (seeded shuffle) so the "problem of the day" cycles through the whole
book without repeats and without consecutive days being related.
"""
import argparse
import os
import random
import re
import sys
import zipfile

SEED = 20260916  # fixed: the daily order must be stable across rebuilds
MAX_COORD = 16   # one byte per stone: 4 bits row, 4 bits col


def read_sgfs(path):
    if os.path.isdir(path):
        for name in sorted(os.listdir(path)):
            if name.endswith(".sgf"):
                with open(os.path.join(path, name), encoding="utf-8") as f:
                    yield name, f.read()
    else:
        with zipfile.ZipFile(path) as z:
            for name in sorted(z.namelist()):
                if name.endswith(".sgf"):
                    yield name, z.read(name).decode("utf-8")


def parse(sgf, name):
    m = re.search(r"GN\[Problem (\d+)\]", sgf)
    if not m:
        raise ValueError(f"{name}: no GN[Problem N]")
    number = int(m.group(1))

    def stones(prop):
        m = re.search(prop + r"((?:\[[a-s]{2}\])+)", sgf)
        if not m:
            return []
        pts = []
        for p in re.findall(r"\[([a-s]{2})\]", m.group(1)):
            col, row = ord(p[0]) - 97, ord(p[1]) - 97
            if col >= MAX_COORD or row >= MAX_COORD:
                raise ValueError(f"{name}: stone {p} does not fit the packed format")
            pts.append((row << 4) | col)
        return pts

    black, white = stones("AB"), stones("AW")
    if len(set(black) & set(white)):
        raise ValueError(f"{name}: a point has both colours")
    if not black and not white:
        raise ValueError(f"{name}: no stones")
    return number, black, white


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("collection", help="collection ZIP or directory of .sgf files")
    ap.add_argument("-o", "--output",
                    default=os.path.join(os.path.dirname(__file__), "..", "include", "tsumego_data.h"))
    args = ap.parse_args()

    problems = {}
    for name, sgf in read_sgfs(args.collection):
        number, black, white = parse(sgf, name)
        if number in problems:
            raise ValueError(f"duplicate problem number {number}")
        problems[number] = (black, white)
    if not problems:
        sys.exit("no .sgf files found")
    count = len(problems)
    if sorted(problems) != list(range(1, count + 1)):
        sys.exit("problem numbers are not contiguous 1..N")

    order = list(range(1, count + 1))
    random.Random(SEED).shuffle(order)

    numbers, offsets, data = [], [], []
    for number in order:
        black, white = problems[number]
        numbers.append(number)
        offsets.append(len(data))
        data += [len(black), len(white)] + black + white
    offsets.append(len(data))
    if len(data) > 0xFFFF:
        sys.exit("data too large for 16-bit offsets")

    def rows(values, per_line, fmt):
        return "\n".join("    " + " ".join(fmt % v + "," for v in values[i:i + per_line])
                         for i in range(0, len(values), per_line))

    src = os.path.basename(args.collection.rstrip("/"))
    out = f"""// Generated by tools/gen_tsumego.py from {src} -- do not edit by hand.
//
// {count} problems from Cho Chikun's "Encyclopedia of Life and Death -
// Elementary", in a fixed pseudo-random order (seed {SEED}) so that the
// problem of the day cycles through the whole book without repeats.
#pragma once
#include <stdint.h>

#define TSUMEGO_COUNT {count}

// The book's problem number of each entry.
static const uint16_t TSUMEGO_NUMBER[TSUMEGO_COUNT] = {{
{rows(numbers, 16, "%3d")}
}};

// Byte offset of each entry in TSUMEGO_DATA; entry TSUMEGO_COUNT is the end.
static const uint16_t TSUMEGO_OFFSET[TSUMEGO_COUNT + 1] = {{
{rows(offsets, 12, "%5d")}
}};

// Per entry: nBlack, nWhite, then one byte per stone, (row << 4) | col,
// black stones first. Row 0 is the top edge, column 0 the left edge.
static const uint8_t TSUMEGO_DATA[{len(data)}] = {{
{rows(data, 16, "0x%02x")}
}};
"""
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {args.output}: {count} problems, {len(data)} data bytes")


if __name__ == "__main__":
    main()
